version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godot
    - mnd
    - noctx
    - tagliatelle
    - usestdlibvars
    - varnamelen
    - wrapcheck
    - godoclint
    - wsl
    - godox
    - mirror
    - musttag
  settings:
    gomoddirectives:
      replace-local: true
    lll:
      line-length: 160
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _test\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - _test\.go$
      - third_party$
      - builtin$
      - examples$