name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
          cache-dependency-path: |
            src/go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7.1
          working-directory: src
